sudo: false
language: c
compiler:
    - gcc
    - clang
os:
    - osx
    - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew upgrade automake libtool; fi
install:
    - git clone https://github.com/ofiwg/libfabric.git
    - cd libfabric
    - ./autogen.sh
    - ./configure --prefix=$HOME
    - make
    - make install
    - cd ..
    - export LDFLAGS="-L$HOME/lib"
    - export CPPFLAGS="-I$HOME/include"
script:
    - ./autogen.sh
    - ./configure --prefix=$HOME
    - make
    - make install
    - make test
